### ISSUE TITLE
It work perfect but is it possible to capture as intended? 

### ISSUE THREAD

**Issue by kotran88** [hiennguyen92/flutter_realtime_object_detection#2]
I'm trying with android latest version 11, but it failed. is it working on android?

**Comment by hiennguyen92** [comment]
Hi @kotran88 can you tell me what the error is?

**Comment by kotran88** [comment]
@hiennguyen92


right after press capture button, it cause error below. 
android version 10  . 
I checked permission, allowed one is mic and camera. not asked permission about file system...
and there's no denied permission listed...
 


/time    ( 4188): Inference took 300
I/flutter ( 4188): recognitions: [{rect: {w: 0.9871838688850403, x: 0.0, h: 0.1638258397579193, y: 0.13047650456428528}, confidenceInClass: 0.6114150285720825, detectedClass: keyboard}]
I/flutter ( 4188): Time detection: 468
3
W/System  ( 4188): A resource failed to call destroy.
D/AndroidRuntime( 4188): Shutting down VM
E/AndroidRuntime( 4188): FATAL EXCEPTION: main
E/AndroidRuntime( 4188): Process: com.hiennv.flutter_realtime_object_detection, PID: 4188
E/AndroidRuntime( 4188): java.lang.IllegalArgumentException: CaptureRequest contains unconfigured Input/Output Surface!
E/AndroidRuntime( 4188): 	at android.hardware.camera2.CaptureRequest.convertSurfaceToStreamId(CaptureRequest.java:738)
E/AndroidRuntime( 4188): 	at android.hardware.camera2.impl.CameraDeviceImpl.submitCaptureRequest(CameraDeviceImpl.java:1079)
E/AndroidRuntime( 4188): 	at android.hardware.camera2.impl.CameraDeviceImpl.capture(CameraDeviceImpl.java:940)
E/AndroidRuntime( 4188): 	at android.hardware.camera2.impl.CameraCaptureSessionImpl.capture(CameraCaptureSessionImpl.java:173)
E/AndroidRuntime( 4188): 	at io.flutter.plugins.camera.Camera.runPictureCapture(Camera.java:581)
E/AndroidRuntime( 4188): 	at io.flutter.plugins.camera.Camera.access$1500(Camera.java:74)
E/AndroidRuntime( 4188): 	at io.flutter.plugins.camera.Camera$3.processCapture(Camera.java:498)
E/AndroidRuntime( 4188): 	at io.flutter.plugins.camera.Camera$3.onCaptureProgressed(Camera.java:455)
E/AndroidRuntime( 4188): 	at android.hardware.camera2.impl.CameraCaptureSessionImpl$1.lambda$onCaptureProgressed$2$CameraCaptureSessionImpl$1(CameraCaptureSessionImpl.java:626)
E/AndroidRuntime( 4188): 	at android.hardware.camera2.impl.-$$Lambda$CameraCaptureSessionImpl$1$7mSdNTTAoYA0D3ITDxzDJKGykz0.run(Unknown Source:8)
E/AndroidRuntime( 4188): 	at android.os.Handler.handleCallback(Handler.java:883)
E/AndroidRuntime( 4188): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime( 4188): 	at android.os.Looper.loop(Looper.java:237)
E/AndroidRuntime( 4188): 	at android.app.ActivityThread.main(ActivityThread.java:8154)
E/AndroidRuntime( 4188): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 4188): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
E/AndroidRuntime( 4188): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
I/Process ( 4188): Sending signal. PID: 4188 SIG: 9
Lost connection to device.

**Comment by kotran88** [comment]
what is weird, as to iOS, it work good even on 15.2 iOS

**Comment by hiennguyen92** [comment]
Ok, i will check android version.

**Comment by kotran88** [comment]
> Ok, i will check android version.

thank you very much! it would be great if you write on GitHub readme to donate you, this repo help me to get through things

**Comment by kotran88** [comment]
I think I found out something. 
on initCamera function, 
if I comment out  below part, then capture is done . 
```

_cameraController.startImageStream((image) async {
        if (!mounted) {
          return;
        }
        await viewModel.runModel(image);
      });
```

anyway that when I press capture button startImageStream is deactivated?
